services:
  order-service:
    container_name: thesis-order-service
    image: thesis-order-service:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9093:9093"
    restart: unless-stopped
    networks:
      thesis-net:
        aliases:
          - order-service
    environment:
      - TZ=UTC
      - SPRING_PROFILES_ACTIVE=docker

networks:
  thesis-net:
    external: true
    name: thesis-net
