spring.application.name=orderService

server.port=8083

spring.datasource.url=jdbc:sqlite:orderdb.db
spring.datasource.driver-class-name=org.sqlite.JDBC

spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

logging.level.root=INFO
logging.level.com.alex.thesis.orderService=DEBUG

# gRPC

grpc.server.port=9093

grpc.client.userService.address=static://localhost:5141
grpc.client.userService.negotiationType=plaintext

grpc.client.productService.address=static://localhost:50051
grpc.client.productService.negotiationType=plaintext