spring.application.name=benchmarkService

server.port=8083

logging.level.root=INFO
logging.level.com.alex.thesis.benchmarkService=INFO

spring.main.banner-mode=off
server.shutdown=graceful
spring.lifecycle.timeout-per-shutdown-phase=20s

# gRPC

grpc.server.port=9093